SELECT CAR_RENTAL_COMPANY_CAR.CAR_ID, CAR_RENTAL_COMPANY_CAR.CAR_TYPE, ROUND(DAILY_FEE * 30 * ( (100- DISCOUNT_RATE)/100 ), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY USING (CAR_ID)
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN USING (CAR_TYPE)
WHERE CAR_TYPE IN ('세단', 'SUV')
    AND CAR_ID NOT IN
    (SELECT CAR_ID
     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
     WHERE START_DATE < '2022-12-01' AND END_DATE >= '2022-11-01' ) 
     AND DURATION_TYPE = '30일 이상'
GROUP BY CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY 
    FEE DESC, CAR_TYPE, CAR_ID DESC;