S = list(input())

num = []
num.append(S.count('a'))
num.append(S.count('b'))
num.append(S.count('c'))
num.append(S.count('d'))
num.append(S.count('e'))
num.append(S.count('f'))
num.append(S.count('g'))
num.append(S.count('h'))
num.append(S.count('i'))
num.append(S.count('j'))
num.append(S.count('k'))
num.append(S.count('l'))
num.append(S.count('m'))
num.append(S.count('n'))
num.append(S.count('o'))
num.append(S.count('p'))
num.append(S.count('q'))
num.append(S.count('r'))
num.append(S.count('s'))
num.append(S.count('t'))
num.append(S.count('u'))
num.append(S.count('v'))
num.append(S.count('w'))
num.append(S.count('x'))
num.append(S.count('y'))
num.append(S.count('z'))

print(*num, sep=' ')