-- 문제 2번
SELECT DISTINCT
	(HISTORY.CAR_ID),
    IF(RENTAL.CAR_ID,'대여중','대여 가능') AS AVAILABILITY
FROM
	CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
LEFT JOIN(
	SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE('2022-10-16') BETWEEN DATE(START_DATE) AND DATE(END_DATE))
	AS RENTAL
ON HISTORY.CAR_ID = RENTAL.CAR_ID
ORDER BY HISTORY.CAR_ID DESC;